### ISSUE TITLE
Looking forward to inference code and checkpoint release

### ISSUE THREAD

**Issue by FeiiYin** [oneThousand1000/3DPortraitGAN#1]
Thanks for the amazing work. Looking forward to inference code and checkpoint release, which can greatly help the community.

**Comment by oneThousand1000** [comment]
Hi there, 

I have released inference codes and checkpoints. BTW, we are now working on a new version of 3DPortraitGAN. Stay tuned!

**Comment by FeiiYin** [comment]
Thanks! Looking forward to your new work!
